spring:
    jpa:
        database: h2
        hibernate:
            ddl-auto: create
        show-sql: true
        open-in-view: true
        properties:
            hibernate.format_sql: true

logging:
    level:
        root: info
        org.hibernate.type.descriptor.sql.BasicBinder: trace